<!--  create a promise that rejects after [3 seconds] use an [async/await] to get its value. Use [try and catch] to handle its error -->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
</head>

<body>
    <script>
        function waitAndReject() {
            return new Promise((resolve, reject) => 
                    {
                        setTimeout(() => {
                            reject("ERROR ‚ùå")
                        }, 3000);
                    })
        }

        async function Result() {
            try {
                let result = await waitAndReject()
                console.log(result);
            } 
            catch (error) {
                console.error(error);
            }
        }

        Result()

    </script>
</body>

</html>